architecture: replication

auth:
  enabled: false

master:
  replicaCount: 1
  persistence:
    enabled: true
  updateStrategy:
    type: RollingUpdate

replica:
  replicaCount: 1
  persistence:
    enabled: true
  updateStrategy:
    type: RollingUpdate

commonLabels:
  app: redis

service:
  type: ClusterIP

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 250m

livenessProbe:
  enabled: true
readinessProbe:
  enabled: true
