architecture: replication
auth:
  enabled: false

master:
  persistence:
    enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate

replica:
  persistence:
    enabled: true
  updateStrategy:
    type: RollingUpdate
