# Default values for custom-redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 6  # Ensuring that you have 6 replicas for high availability

image:
  repository: redis  # Corrected to use Redis image repository
  pullPolicy: IfNotPresent
  tag: ""  # You can specify the version or leave it blank to use the default one

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 6379  # Redis default port

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

# Adding rolling update strategy to ensure zero downtime
deployment:
  updateStrategy:
    type: RollingUpdate  # Specifies that a rolling update strategy should be used
    rollingUpdate:
      maxUnavailable: 1  # Ensures that only one pod is unavailable at a time during the update
      maxSurge: 1  # Ensures that at least one additional pod will be created during the update for high availability
